name: Build and upload into PyPI

# Manually dispatch
on: workflow_dispatch
# push:
#  pull_request:
#  release:
#    types:
#      - published


# Only build CPython 3.6+, skip Win32, Linux i686, and musllinux (inspired by APW's gala workflow)
# C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x86\rc.exe              

env:
    CIBW_BUILD: "cp37-* cp38-* cp39-* cp310-* cp311*"
    CIBW_SKIP: "*-win32 *-manylinux_i686 *-musllinux*"
    CIBW_ENVIRONMENT_WINDOWS: >
        PATH="$PATH;C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.22000.0\\x86"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-11]

    steps:
      - uses: actions/checkout@v4
      
#      - uses: actions/setup-python@v3
#        name: Install Python
#        with:
#          python-version: '3.11'
#          
#      - name: Install cibuildwheel
#        run: python -m pip install cibuildwheel==2.16.2     

      - name: Install dependencies
        run: pip install numpy

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
#        run: python -m cibuildwheel --output-dir wheelhouse


      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl


  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

#      - uses: actions/setup-python@v3
#        name: Install Python
#        with:
#          python-version: '3.11'

      - name: Install dependencies
        run: pip install numpy

      - name: Build sdist
#        run: python setup.py sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz


  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    # upload to PyPI on every tag starting with 'v'
    # if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')
    # alternatively, to publish when a GitHub Release is created, use the following rule:
    # if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1
        with:
          user: __token__
          password: ${{ secrets.pypi_api_token }}
          # To test: 
#          password: ${{ secrets.test_pypi_api_token }}
#          repository_url: https://test.pypi.org/legacy/
