name: Testing for Windows GitHub Actions cibuildwheel issue

on:
  push:
  
jobs:
  findinfo:
    name: Get info where rs.exe is
    runs-on: windows-2019
    
    steps:
     - name: Check Windows VS environment
       run: |
            function Invoke-VSDevEnvironment { 
              $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
              $installationPath = & $vswhere -prerelease -legacy -latest -property installationPath
              $Command = Join-Path $installationPath "Common7\Tools\vsdevcmd.bat"
                & "${env:COMSPEC}" /s /c "`"$Command`" -no_logo && set" | Foreach-Object {
                if ($_ -match '^([^=]+)=(.*)') {
                      [System.Environment]::SetEnvironmentVariable($matches[1], $matches[2])
                }
              }
            }
            Invoke-VSDevEnvironment
            Get-Command rc.exe | Format-Table -AutoSize

# Output:
# C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x86\rc.exe